[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "client"
version = "1.0.0"
dependencies = [
    'importlib-metadata; python_version<"3.8"',
    'pysimplegui',
    'rich-click',
    'rich'
]

[project.scripts]
client="client:cli"
   
